"""Scenario A — Couple Dinner (18 turns)."""

from .base import Conversation, Turn

COUPLE_DINNER = Conversation(
    name="A — Couple Dinner",
    table_id="T1",
    party_size=2,
    turns=[
        Turn("Chào em, bàn mình có 2 người. Cho anh xem menu có gì hot hôm nay đi",
             "greeting + menu browse", "SEARCH"),
        Turn("Hải sản ở đây có món gì ngon? Anh với vợ thích ốc với tôm, em gợi ý vài món đi",
             "recommendation search", "SEARCH"),
        Turn("Ốc Hương Xốt Trứng Muối ngon không em? Có cay không? Mà bao nhiêu 1 phần?",
             "multi-question about one dish", "SEARCH"),
        Turn("Ừ nghe cũng được. Mà ngoài món đó ra Ốc Hương còn làm kiểu gì khác không em?",
             "follow-up diversity — must NOT repeat Trứng Muối", "SEARCH"),
        Turn("Tôm Càng Xanh Nướng Phô Mai phần ăn bao nhiêu con? Có đủ 2 người ăn không?",
             "portion query — may not be in menu data", "SEARCH"),
        Turn("Cho 2 phần Ốc Hương Xốt Trứng Muối với 1 Tôm Càng Xanh Nướng Phô Mai đi",
             "multi-item order", "ORDER"),
        Turn("À mà vợ anh thích hàu hơn tôm, bỏ Tôm Càng Xanh đi, cho anh 3 con Hàu Nướng Phô Mai thay",
             "substitution (remove + add)", "ORDER"),
        Turn("Với cho 1 Bia Tiger Bạc. Mà khoan, Tiger nghe đắng quá, có bia nào nhẹ hơn không em?",
             "add order then SEARCH for alternative", "SEARCH"),
        Turn("Vậy lấy 2 Bia Sài Gòn đi. Cho anh hỏi thêm Ốc Móng Tay ở đây có những món gì?",
             "seamless add + dish group query", "ORDER"),
        Turn("Cho thêm 1 dĩa Khoai Tây Lắc Phô Mai cho vợ. Có món chay nào nữa không em?",
             "order + diet-constrained SEARCH", "ORDER"),
        Turn("Gỏi Xoài Ốc Giác giá bao nhiêu? Rồi cho anh 1 phần luôn, lưu ý bớt cay nha",
             "price query then order with special_request", "ORDER"),
        Turn("Em ơi cho anh xem tổng đơn hiện tại đi",
             "cart review", "SEARCH"),
        Turn("Bỏ Bia Tiger Bạc đi — à mà anh đã bỏ rồi hả? Thôi xem lại đơn đi",
             "self-correcting, tiger already removed", "ORDER"),
        Turn("Lấy thêm 1 Sò Điệp Nướng Phô Mai với 2 Cháo Hàu đi. Giờ chốt đơn nha em",
             "multi-item add + implicit confirm", "ORDER"),
        Turn("Ok xác nhận",
             "confirm", "ORDER_CONFIRM"),
        Turn("Tính tiền cho anh",
             "request payment", "PAYMENT"),
        Turn("Anh chuyển khoản xong rồi, kiểm tra giúp anh",
             "verify payment", "PAYMENT"),
    ],
)
