#!/usr/bin/env python3
"""Aggregate evaluate/logs into thesis-ready markdown + CSV tables."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from evaluate.common import logs_root


def _load_summaries(root: Path) -> list[dict]:
    out = []
    if not root.is_dir():
        return out
    for child in sorted(root.iterdir()):
        summary = child / 'summary.json'
        if summary.is_file():
            data = json.loads(summary.read_text(encoding='utf-8'))
            data['_run_dir'] = str(child)
            out.append(data)
    return out


def _latest_by_test(summaries: list[dict]) -> dict[str, dict]:
    """Prefer newest run per logical test key (nav split by align flag)."""
    latest: dict[str, dict] = {}
    for s in summaries:
        test = s.get('test')
        if test == 'navigation':
            key = 'navigation_align_on' if s.get('enable_visual_align') else 'navigation_align_off'
        else:
            key = str(test)
        # runs are sorted by name (timestamp prefix) — later overwrite = newer
        latest[key] = s
    return latest


def _md_escape(s) -> str:
    return '' if s is None else str(s)


def build_markdown(latest: dict[str, dict]) -> str:
    lines: list[str] = []
    lines.append('# Chapter 5 — auto-filled experiment tables')
    lines.append('')
    lines.append('Generated by `eval_summarize` from `evaluate/logs/`.')
    lines.append('')

    odom = latest.get('odometry')
    lines.append('## Table 5.1 — Odometry return-to-start error')
    lines.append('')
    lines.append('| Trials | Position (cm) mean ± std | Heading (deg) mean ± std |')
    lines.append('|--------|--------------------------|---------------------------|')
    if odom:
        n = odom.get('n_ok', odom.get('n_trials'))
        lines.append(
            f"| {n} | {_md_escape(odom.get('position_cm_mean_std'))} | "
            f"{_md_escape(odom.get('heading_deg_mean_std'))} |")
    else:
        lines.append('| — | **[missing run]** | **[missing run]** |')
    lines.append('')

    maps = latest.get('map_summary')
    lines.append('## Table 5.2 — Mapping summary')
    lines.append('')
    lines.append('| Duration | Loop closures (geom. / ArUco) | Resolution | Consistency |')
    lines.append('|----------|-------------------------------|------------|-------------|')
    if maps:
        dur = maps.get('duration_min')
        dur_s = f'{dur} min' if dur is not None else '**[TBD]** min'
        geom = maps.get('loop_closures_geom')
        aruco = maps.get('loop_closures_aruco')
        res = maps.get('resolution_m')
        cons = maps.get('consistency') or '**[TBD]**'
        lines.append(
            f'| {dur_s} | {geom} / {aruco} | {res} m | {cons} |')
    else:
        lines.append('| **[missing]** | **[missing]** | 0.05 m | **[missing]** |')
    lines.append('')

    loc = latest.get('localization')
    lines.append('## Table 5.3 — Localization drift')
    lines.append('')
    lines.append(
        '| Checkpoint | $|\\Delta x|$ (cm) | $|\\Delta y|$ (cm) | '
        '$|\\Delta \\psi|$ (deg) |')
    lines.append('|------------|-------------------|-------------------|----------------------|')
    if loc:
        t = loc.get('table_1_arrival', {})
        d = loc.get('dock_return', {})
        lines.append(
            f"| Table 1 arrival | {_md_escape(t.get('abs_dx_cm'))} | "
            f"{_md_escape(t.get('abs_dy_cm'))} | {_md_escape(t.get('abs_dpsi_deg'))} |")
        lines.append(
            f"| Dock return | {_md_escape(d.get('abs_dx_cm'))} | "
            f"{_md_escape(d.get('abs_dy_cm'))} | {_md_escape(d.get('abs_dpsi_deg'))} |")
    else:
        lines.append('| Table 1 arrival | **[missing]** | **[missing]** | **[missing]** |')
        lines.append('| Dock return | **[missing]** | **[missing]** | **[missing]** |')
    lines.append('')

    def nav_table(title: str, key: str) -> None:
        lines.append(f'## {title}')
        lines.append('')
        lines.append(
            '| Trials | Nav success | Trip time (s) | Lateral err (cm) | '
            'Range err (cm) | $|\\Delta \\psi|$ (deg) |')
        lines.append(
            '|--------|-------------|---------------|------------------|----------------|'
            '----------------------|')
        nav = latest.get(key)
        if nav:
            n = nav.get('n_trials')
            rate = nav.get('nav_success_rate_pct')
            rate_s = f'{rate:.0f}%' if isinstance(rate, (int, float)) else rate
            lines.append(
                f"| {n} | {_md_escape(rate_s)} | "
                f"{_md_escape(nav.get('trip_time_s_mean_std'))} | "
                f"{_md_escape(nav.get('lateral_err_cm_mean_std'))} | "
                f"{_md_escape(nav.get('range_err_cm_mean_std'))} | "
                f"{_md_escape(nav.get('abs_dpsi_deg_mean_std'))} |")
        else:
            lines.append(
                '| — | **[missing]** | **[missing]** | **[missing]** | '
                '**[missing]** | **[missing]** |')
        lines.append('')

    nav_table('Table 5.4 — With visual align', 'navigation_align_on')
    nav_table('Table 5.5 — Without visual align', 'navigation_align_off')

    lines.append('## Table 5.6 — Traceability')
    lines.append('')
    lines.append('| Objective | Experiment | Result |')
    lines.append('|-----------|------------|--------|')
    odom_pos = odom.get('position_cm_mean_std') if odom else '**[TBD]**'
    loc_note = 'see Table 5.3' if loc else '**[TBD]**'
    nav_on = latest.get('navigation_align_on')
    if nav_on:
        nav_res = (
            f"{nav_on.get('nav_success_rate_pct')}% / "
            f"{nav_on.get('lateral_err_cm_mean_std')} cm")
    else:
        nav_res = '**[TBD]**'
    lines.append(f'| EKF-fused odometry return-to-start accuracy | Odometry accuracy test | {odom_pos} cm |')
    lines.append(f'| RTAB-Map map quality and localization drift | Map building and localization test | {loc_note} |')
    lines.append(f'| Nav2 delivery success and Table 1 docking precision | Navigation and docking test | {nav_res} |')
    lines.append('')
    return '\n'.join(lines)


def build_csv_rows(latest: dict[str, dict]) -> list[dict]:
    rows = []
    for key, s in latest.items():
        rows.append({
            'key': key,
            'test': s.get('test'),
            'thesis_table': s.get('thesis_table'),
            'run_dir': s.get('_run_dir'),
            'summary_json': json.dumps(s, ensure_ascii=False),
        })
    return rows


def main(args=None) -> None:
    parser = argparse.ArgumentParser(description='Summarize evaluate logs for thesis tables')
    parser.add_argument(
        '--logs', type=Path, default=None,
        help='Logs root (default: evaluate/logs)')
    parser.add_argument(
        '--out-dir', type=Path, default=None,
        help='Output directory (default: same as logs root)')
    ns = parser.parse_args(args=args)

    root = ns.logs or logs_root()
    out_dir = ns.out_dir or root
    out_dir.mkdir(parents=True, exist_ok=True)

    summaries = _load_summaries(root)
    latest = _latest_by_test(summaries)
    md = build_markdown(latest)
    md_path = out_dir / 'thesis_tables.md'
    md_path.write_text(md, encoding='utf-8')

    csv_path = out_dir / 'thesis_tables.csv'
    rows = build_csv_rows(latest)
    with csv_path.open('w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['key', 'test', 'thesis_table', 'run_dir', 'summary_json'])
        writer.writeheader()
        writer.writerows(rows)

    print(f'Loaded {len(summaries)} run(s), {len(latest)} latest key(s).')
    print(f'Wrote {md_path}')
    print(f'Wrote {csv_path}')


if __name__ == '__main__':
    main()
